info = CHALLENGES AND ADVANCEMENTS IN WIRE ARC ADDITIVE MANUFACTURING
INTRODUCTION
Additive manufacturing (AM) is a manufacturing technology that builds three dimensional objects from Computer Aided Design (CAD) model data by adding material like plastic, metal or concrete using layer by layer build-up approach. This is a relatively recent manufacturing method and it has become a key area of interest in multiple industrial sectors. Additive manufacturing can be used to manufacture complex geometries including internal part details that are not possible to manufacture using machining and moulding processes. Additive manufacturing has many different processes like photopolymerization, Powder Bed Fusion, Sheet Lamination etc including Wire Arc Additive Manufacturing (WAAM).
Wire Arc Additive Manufacturing is a variation of Direct Energy Deposition Technology using arc welding process to three dimensionally print metal parts. WAAM works by melting metal wire using an electric arc as the heat source and building the shape upon a substrate material (a base plate) that can be cut from once finished. WAAM is a comparatively cheaper process than other additive manufacturing processes, as the others require specific equipment and materials. Other Additive manufacturing processes uses powder or some other feedstock materials making it more prone to formation of defects such as pores, which can hamper the structural integrity of the parts. The deposition rates are significantly higher, hence allowing the manufacture of large metallic structural parts in short times.
WAAM has a wide variety of areas where it can be applied. Cranfield University has produced one of the largest 3D metal titanium parts in the U.K. Measuring 1.2m, the part forms a main structural element of an aircraft wing and took just 37 hours to build from a digital model. Previously this process would have taken weeks. Under marine applications, WAAM can replace the traditional method of casting since it can create propellers much faster as casting requires long lead time since the process involves making a mold, casting it, and then processing it. WAAM can also be applied to automobile sector to produce complex parts that may not be possible with traditional manufacturing techniques. This can be seen in sectors such as motor sport and specialist road vehicles where the production runs are limited.
First patented in 1920, WAAM is probably the oldest, outwardly simplest, but least talked about of the range of additive manufacturing processes. Using wire as feedstock, the basic process has been used to perform local repairs on damaged or worn components, and to manufacture round components and pressure vessels for decades. However, the advent of high quality computer aided design and manufacturing (CAD/CAM) software has made AM in general possible, with WAAM in particular being an area of significant development. With a resolution of approximately 1mm and deposition rate between 1 and 10kg/hour or more (depending on arc source), the operating window of WAAM is between, and complementary to, highly accurate but slower laser-based systems and less accurate high-deposition-rate multi-arc plasma and electron beam systems.
WAAM is one of the several prominent 3D printing techniques where significant advances have been made in the last five years

n=0
for char in info:
    if char == " ":
        n =n
    else:
        n += 1
print(n)